name: osmtest

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_osm_plugin: ^0.42.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  dynamic_color: ^1.5.4
  vector_map_tiles: ^3.1.4
  flutter_map_tile_caching: ^7.0.0
  cached_network_image: ^3.2.3
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.17
  flutter_phoenix: ^1.1.0
  restart_app: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
